### ISSUE TITLE
Please make this repo private.

### ISSUE THREAD

**Issue by Blind4Basics** [hevalhazalkurt/codewars_python_solutions#2]
Hello,

You should read [Codewars code of conduct](https://docs.codewars.com/community/rules), specifically the last bullet point of the "rules" section. So You should make this repo private.

Thx

**Comment by hevalhazalkurt** [comment]
Hi @Blind4Basics 

I totally understand your concern and thank you for creating Codewars first. However, these solutions don't show that I am a cheater, but that those who benefit from these solutions are cheaters, and you are blocking me because you cannot prevent them? I'm not using this as a resume or for any other professional purpose. I don't think copying a solution and getting a higher rank on Codewars can help on any technical interviews. After all, I'm expected to solve questions in technical interviews, not copy them. You can't cheat on professional life, so... I just can hope my "own" solutions will be useful for those learning programming. I also benefited from similar repos at the time and it didn't make me a cheater, just seeing the solutions of other developers improved me, expanded my approaches, and prepared me to make better solutions for the next questions.

Codewars is an environment where I enjoy solving problems, improving myself as a programmer, and I thought that was its main purpose. To learn more, progress more, develop more, and be better. How will we be a better industry if we can't share what we know with each other? I don't think it's more important than that if someone copied two question answers from here and got a better rank in Codewars. Please keep in your mind, you cannot prevent the cheaters by preventing others who really contribute to you. If someone has an idea about copying a solution he or she can do it anyway. Even there isn't any repo about it, he/she can get help from a friend and push the system. When the time comes will you block the friend? 😊 

Like I said before, you can block me or you can have a different approach about it and we can make Codewars bigger and better. It's your choice.

P.S. In addition, it is useful to find those who publish paid solutions on Patreon or Youtube instead of those who only share their own solutions in open-source.

**Comment by Blind4Basics** [comment]
Hello,

I never saw your reply, sorry.

> thank you for creating Codewars first. 

I'm not one of CW's creators, just a mod there.

> these solutions don't show that I am a cheater,

Nobody ever said that.

> but that those who benefit from these solutions are cheaters,

Definitely. You have no idea how many I found, using your solutions (I actually landed here again today, following through the github profile of one of them)

> you are blocking me because you cannot prevent them? 

"blocking"? you mean here? an issue isn't blocking anything, as far as I know.
Or did your CW account get locked? No, I found it and it isn't locked.
Hence, I don't see anything to reply to the remaining part of your first § (since it's based on a wrong initial assumption, apparently).
Oh, still:

> You can't cheat on professional life, so... I just can hope my "own" solutions will be useful for those learning programming. 

1. ofc one can. Like anywhere else ;)
2. thing is, ppl using solutions found on github will _NEVER_ learn anything. 99% of them are just hunting for point. So even if your intent is altruist, the actual effect is rather the opposite.

> I also benefited from similar repos at the time and it didn't make me a cheater
My very honest congratulations to you: you're in the 1% ;) (I'm absolutely serious, here)

> just seeing the solutions of other developers improved me, expanded my approaches, and prepared me to make better solutions for the next questions.
solutions can be seen on CW as well. People _CAN_ forfeit the kata to see them and learn.

---

let's keep this shorter:

if you don't want to make this repo private, I'd say it's sort of your problem. I'm not delusional about the way it is used. ;)
On the other hand, what you could do is to make it less discoverable (removing "codewars" from any repo/directory/file name, at the very least)

--

Your PS is quite intriguing. Like... Are you saying you intent to gain money or an equivalent through this kind of repo? That would be quite on the opposite train of thoughts, compared to your "altruist arguments" from the beginning of your message. 

Cheers
